services:
  comfyui-worker:
    image: duodecanol/worker-comfyui:latest-base
    pull_policy: never
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    develop:
      watch:
        - action: sync
          path: ./src
          target: /src
          ignore:
            - node_modules/
            - .venv/
        - action: rebuild
          path: Dockerfile
    environment:
      SERVE_API_LOCALLY: true
      COMFY_VRAM_MANAGEMENT_MODE: lowvram
    ports:
      - "8000:8000"
      - "8188:8188"
    volumes:
      - ./data/comfyui/output:/comfyui/output
      - ./data/runpod-volume:/runpod-volume
